name: Auto Assign
on:
  pull_request:
    types:
      - opened
jobs:
  auto-assign:
    runs-on: ubuntu-22.04
    steps:
      - name: Set build URL to commit status
        run: |
          curl \
          --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "{
            \"assignees\": [\"${{ github.actor }}\"]
          }"
